### ISSUE TITLE
建议增加 Jwt 的支持

### ISSUE THREAD

**Issue by andy236726493** [lizhichao/one#13]
建议增加 Jwt 的支持

**Comment by lizhichao** [comment]
支持的

**Comment by andy236726493** [comment]
没看到文档介绍啊，文档要完善一下。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"vic"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月4日(星期一) 下午3:01
收件人:&nbsp;"lizhichao/one"<one@noreply.github.com&gt;;
抄送:&nbsp;"andyzhu"<236726493@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lizhichao/one] 建议增加 Jwt 的支持 (#13)




支持的

**Comment by andy236726493** [comment]
建议加QQ群，二维码用微信的，qq支付不是每个人都有的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"vic"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月4日(星期一) 下午3:01
收件人:&nbsp;"lizhichao/one"<one@noreply.github.com&gt;;
抄送:&nbsp;"andyzhu"<236726493@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lizhichao/one] 建议增加 Jwt 的支持 (#13)




支持的

**Comment by lizhichao** [comment]
可以考虑建个微信群
