### ISSUE TITLE
赶紧更新啊

### ISSUE THREAD

**Issue by wo642436249** [lizhichao/one#15]
赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊赶紧更新啊

**Comment by lizhichao** [comment]
目前常用的功能都有了，也没有很着急的新功能，
也没有发现需要修复的bug。不着急

**Comment by wo642436249** [comment]
那你赶紧推广啊，用的人多了，就更新频繁了

**Comment by lizhichao** [comment]
这的靠大家了
