### ISSUE TITLE
swoole环境,支持$_GET,$_POST这种方式获取吗?像restful的put参数如何获取

### ISSUE THREAD

**Issue by xilin693** [lizhichao/one#20]
是否都要通过request对象来获取,文档上没提到这块

**Comment by emei8** [comment]
都可以，当前使用的是thinkphp框架的接收参数方式，也可根据自己的方式接收参数


 
---原始邮件---
发件人: "xilin693"<notifications@github.com&gt;
发送时间: 2020年8月18日(星期二) 上午10:36
收件人: "lizhichao/one"<one@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [lizhichao/one] 支持$_GET,$_POST这种获取获取吗?像restful的put参数如何获取 (#20)




 
是否都要通过request对象来获取,文档上没提到这块

**Comment by lizhichao** [comment]
客户端提交的信息都在 request 对象上面，在`fpm`和`swoole`模式都通过request 来获取。
默认提供了`$this->request->get()`,`$this->request->post()` 其他信息可以通过`$this->request->input()` 来获取

**Comment by xilin693** [comment]
> 客户端提交的信息都在 request 对象上面，在`fpm`和`swoole`模式都通过request 来获取。
> 默认提供了`$this->request->get()`,`$this->request->post()` 其他信息可以通过`$this->request->input()` 来获取

收到,谢谢
