### ISSUE TITLE
框架有没有封装退出的方法,用于调试的

### ISSUE THREAD

**Issue by xilin693** [lizhichao/one#21]
比如说我需要在确认代码在运行到某个位置是否正常 ,我可能会var_dump($param)或echo $param然后执行exit. swoole不支持exit,所以我现在使用的是throw new \Exception($param)的方式来调试,这样one框架有返回一个500的json,里边可以看到$param的信息,有没有更好的方法

**Comment by lizhichao** [comment]
可以通过fpm模式调试 也可以打印日志 ，通过请求id查看这个请求的日志信息 里面有文件名字和行号

**Comment by xilin693** [comment]
> 可以通过fpm模式调试 也可以打印日志 ，通过请求id查看这个请求的日志信息 里面有文件名字和行号
好的,那我还是使用fpm模式作调试吧,比较简单.
