### ISSUE TITLE
Breaking change detected in patch level

### ISSUE THREAD

**Issue by waghanza** [lizhichao/one#23]
Hi @lizhichao,

I can see that this dependency has been introduce in **2.0.23**, but was not in **2.0.22**
https://github.com/lizhichao/one/blob/8ab51aec0ce645c1f952b5628e56e800999437cc/composer.json#L22

This mean `bcmath` is now required. As I have not this extension, this break my CI (hopefully it is not a production).

BTW, I have fixed this in https://github.com/the-benchmarker/web-frameworks/pull/3632

Regards,

**Comment by lizhichao** [comment]
@waghanza   thank you，`lizhichao/one-ck` A is a clickhouse Tcp connector，There is no database operation here, it will not run automatically

**Comment by waghanza** [comment]
but having it in composer manifest fails (since composer check if `ext-bcmath` is setup)

**Comment by lizhichao** [comment]
嗯，确实有这个问题

**Comment by waghanza** [comment]
> 嗯，确实有这个问题

Do not understand any Chinese 😄

**Comment by lizhichao** [comment]
> > 嗯，确实有这个问题
> 
> Do not understand any Chinese 😄

You're right. The composer installation will require this extension `ext-bcmath` if it is not used
