### ISSUE TITLE
基于one，对view层做了点小小改动~

### ISSUE THREAD

**Issue by ClanceyHuang** [lizhichao/one#24]
因为某些原因，并没有用vue等框架进行前后端分离，我基于one简单改了点东西，提供对view层的支持，大佬们抽空看看可不可以提交个pr~
之前通过one学到了很多，现在看看能不能做点贡献，正向回馈给大家~
有不对的地方希望大家指出~
变更文档如下：

[对one相关的改动](https://github.com/ClanceyHuang/one-app/blob/master/View.md)

**Comment by lizhichao** [comment]
感谢支持。对模板的需求有越来越少了，不建议集成了。
one不想做的面面俱到，定位是把常用的做的好用且稳定就好了，模板引擎有更专业的 如：symfony的twig。
你自己想改造可以直接在one-app里面修改就可以了，one-app定位是one的项目具体化，我这里写的算是一个范例，你可以任意改动，one有bug之类的修复，也不影响升级。

**Comment by ClanceyHuang** [comment]
好的~
