### ISSUE TITLE
希望能持续更新

### ISSUE THREAD

**Issue by hero2040407** [lizhichao/one#6]
希望持续更新，orm这块有了连接池就应该支持协程操作了吧

**Comment by lizhichao** [comment]
会长期支持。完全支持协程

**Comment by hero2040407** [comment]
像fpm模式下成熟的框架已经非常多了，应该完全转向swoole，为了适应fpm模式，必然导致框架的性能无法达到最大化，现在swoole体系下成熟的框架比较少，尤其是好用的orm(原谅我写惯了orm原生都不怎么会了)，如果能在这个方向上用把劲也许会更好，至于rpc，说真的大部分phper根本没能力达到驾驭它的地步，使用的机会太少了，毕竟java生态太完善了，swoole和php7迟了一步

**Comment by lizhichao** [comment]
嗯 one 易用性 和 性能 在php框架里面都是非常靠前的。
兼容fpm不会有多性影响，不用担心。
我也非常喜欢用orm，所以one有个非常好用的orm， 常用功能都覆盖 包括 表关系  调用方法和 laravel 类似，但是更灵活。
你甚至可以 User::with('ariticle')->query("select * from user where id =1") 这样用
