### ISSUE TITLE
有增加actor的计划吗?

### ISSUE THREAD

**Issue by lihaotian0607** [lizhichao/one#8]
有增加actor的计划吗?
游戏开发使用actor貌似更快捷 ,如果自己去写的话有有点繁琐 后期有计划增加吗

**Comment by lizhichao** [comment]
后续会增加

**Comment by lizhichao** [comment]
@lihaotian0607  已支持

**Comment by lihaotian0607** [comment]
强,这么快就可以了!!!

**Comment by lizhichao** [comment]
@lihaotian0607 https://github.com/lizhichao/one-app/blob/actor_demo/README.md 例子
